### ISSUE TITLE
[Feature request] Add option to break the hold down loop with the actual key

### ISSUE THREAD

**Issue by neube3** [Douile/logitech-toggle-keys#4]
Currently, if I have e.g. bound "w" for G11 mouse button with the script, it will keep pressing "w" until I press G11 again.

It would be great (and convenient) to have the actual "w" button break the loop as well. Sadly, I cannot think of a way to have the loop re-set (as in "G11, w, G11" starting, breaking and starting the loop again, instead of having to use G11 twice, as in "G11, w, G11, G11") - perhaps you could think of a way to do it properly.

**Comment by Douile** [comment]
@neube3 sorry it took me so long to see this
I will look into adding this soon

**Comment by Douile** [comment]
Unfortunately this is not possible as they current API doesn't allow for detection of keyboard press events

It would be possible to make something like this using software such as autohotkey though.
